### ISSUE TITLE
Ajax request, 302 moved temporarily - clear $_POST.

### ISSUE THREAD

**Issue by lnxmen** [Panthera-Framework/panthera#347]
It is strange issue, because I do not know how to reproduce this bug. More or less, it occurs when request is made and `Panthera` adds `_` in the end of url as `$_GET` parameter with long number. Can't say what it actually is. What I know, it's apparently related to RainTPL, but sometimes makes Panthera completely *unusable*.
When redirection is made, every `$_POST` value is no longer available. Then, PHP controller do not know what to do with given (or rather not) data.

Lastly I got this bug there:
Url: `http://pantheraUrl/_ajax.php?display=users&cat=admin&action=account&uid=X`
Popup: `editUser`
I tried to change user password. I got  bad looking message (in raw json array), that UID is not given.

First request (as you can see, uid is fulfilled):
![image](https://cloud.githubusercontent.com/assets/908744/5560017/e78de33c-8d6a-11e4-81cc-5e2a5cb6d739.png)
Redirected request (no form data - no uid sent):
![image](https://cloud.githubusercontent.com/assets/908744/5560032/4f62c266-8d6b-11e4-9749-9e0555b96684.png)

What it produces:
![image](https://cloud.githubusercontent.com/assets/908744/5560034/78ee00aa-8d6b-11e4-8aff-7e648b964533.png)

**Comment by webnull** [comment]
Are you sure that the redirect is not coming from javascript?

**Comment by lnxmen** [comment]
Yes, it's not related to javascript.
We had similar issue with Facebook authentication, do you remember?
