### ISSUE TITLE
RainTPL4. Bugs, errors, ideas...

### ISSUE THREAD

**Issue by lnxmen** [Panthera-Framework/panthera#349]
This issue is created to **make Panthera Framework usable** again. Now, due to big improvements in RainTPL a part of our project does not work - for instance, I can't get settings page compiled properly.

![image](https://cloud.githubusercontent.com/assets/908744/7670368/225ddf7a-fca2-11e4-8c6a-df36f373cdda.png)

@webnull, you are the most knowledgeable person in this project. Where should we start?

**Comment by webnull** [comment]
It's normal. We will have to rewrite pantheraTemplate for the new RainTPL4 and to clean up some things.
